name: Run Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm install

      - name: Start the app
        run: npm run dev &
        env:
          CI: true

      - name: Wait for app to start
        run: npx wait-on http://localhost:3000

      - name: Run Cypress E2E Tests
        run: npx cypress run --e2e

  component-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Component Tests
        run: npx cypress run --component

  deploy:
    needs: [e2e-tests, component-tests] # only runs if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          ssh ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            cd /var/www/your-app-folder # path on your Azure VM
            git pull origin main
            npm install
            npm run build
            pm2 restart your-app-name # or however you run the app
          EOF
