name: Run Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm install

      - name: Start the app
        run: npm run dev &
        env:
          CI: true

      - name: Wait for app to start
        run: npx wait-on http://localhost:3000

      - name: Run Cypress E2E Tests
        run: npx cypress run --e2e

  component-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Component Tests
        run: npx cypress run --component

  deploy:
    needs: [e2e-tests, component-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 20.244.18.120
          username: raunak2000
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/raunak2000/cypress_testing
            git pull origin main
            npm install
            npm run build
            pm2 restart app || pm2 start npm --name app -- run start
#it should work now
